services:
  rest-api-demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-rest-api-demo
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped